### ISSUE TITLE
Big issue: lacking pênis

### ISSUE THREAD

**Issue by gmelodie** [BrunoGomesCoelho/BrunoGomesCoelho#1]
I think adding a pênis would be greatly beneficial. Here are some illustrations of how this could be implemented

![](https://media.giphy.com/media/3kD2JsjlXSkbAywC7C/giphy.gif?cid=ecf05e47efegouwvfc4ro9akpn0yvaob057yaun9s6je4av3&rid=giphy.gif&ct=g)

![](https://media.giphy.com/media/3oEduH8xILFeHADEju/giphy.gif?cid=ecf05e47u6yclkybwve4we1yasecz64xhgjwxy14xwdiigxu&rid=giphy.gif&ct=g)

**Comment by BrunoGomesCoelho** [comment]
Feel free to open a PR with your own pênis contribution and it will be analyzed!
